# Generated by Django 4.2 on 2026-04-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Admitionwala IT Services', max_length=200)),
                ('company_description', models.TextField(help_text='Company overview and mission')),
                ('vision', models.TextField(help_text='Company vision statement')),
                ('mission', models.TextField(help_text='Company mission statement')),
                ('about_founder', models.TextField(help_text='Information about the founder')),
                ('countries_served', models.CharField(default='India, UK, USA', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('founder', 'Founder & CEO'), ('technical_lead', 'Technical Lead'), ('marketing_head', 'Marketing Head'), ('developer', 'Developer'), ('designer', 'Designer'), ('manager', 'Project Manager'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Team member bio and expertise')),
                ('image', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('order', models.IntegerField(default=0, help_text='Display order on page')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
                'ordering': ['order', 'name'],
            },
        ),
    ]
