import random
import re

class SiteArchitect:
    def __init__(self, user_requirements):
        self.raw_input = user_requirements.lower()
        self.config = self._extract_config()
        
    def _extract_config(self):
        """Advanced Neural Requirement Parsing (Simulated LLM)"""
        config = {
            'type': 'business',
            'theme': 'modern',
            'accent': '#10b981', # Emerald
            'name': 'AI Synthesized Project',
            'keywords': ['technology', 'modern', 'enterprise'],
            'features': ['hero', 'services', 'portfolio', 'contact']
        }
        
        # Industry detection
        industry_map = {
            'ecommerce': ['shop', 'store', 'sell', 'product', 'buy', 'commerce'],
            'portfolio': ['work', 'showcase', 'creative', 'gallery', 'personal', 'freelancer'],
            'saas': ['app', 'software', 'platform', 'tool', 'dashboard'],
            'restaurant': ['food', 'cafe', 'menu', 'dining', 'eat'],
            'realestate': ['property', 'home', 'house', 'apartment', 'realty']
        }
        
        for ind, keywords in industry_map.items():
            if any(k in self.raw_input for k in keywords):
                config['type'] = ind
                config['keywords'] = keywords
                break
                
        # Color/Theme detection
        if 'dark' in self.raw_input or 'black' in self.raw_input:
            config['theme'] = 'dark'
        elif 'blue' in self.raw_input:
            config['accent'] = '#2563eb' # Blue-600
        elif 'minimal' in self.raw_input:
            config['theme'] = 'minimalist'
            
        return config

    def generate_manifest(self):
        """Synthesizes a full multi-file website project"""
        # 1. Generate Image Assets (Topic-Aware Unsplash Source)
        keyword_str = ",".join(self.config['keywords'][:2])
        images = {
            'hero': f"https://images.unsplash.com/photo-1498050108023-c5249f4df085?q=80&w=1600&fit=crop", # dynamic fallback
            'feat1': f"https://source.unsplash.com/featured/?{keyword_str},1",
            'feat2': f"https://source.unsplash.com/featured/?{keyword_str},2",
            'feat3': f"https://source.unsplash.com/featured/?{keyword_str},3",
        }

        # 2. Generate Pitch Text
        pitch = self._generate_sales_pitch()

        # 3. Assemble Multi-File Structure
        manifest = {
            'index.html': self._build_html(images),
            'assets/css/style.css': self._build_css(),
            'assets/js/main.js': self._build_js(),
            'README.md': self._build_readme()
        }
        
        return {
            'files': manifest,
            'pitch': pitch
        }

    def _generate_sales_pitch(self):
        """Synthesizes a persuasive sales introduction based on logic"""
        t = self.config['type']
        return f"Greetings! I have synthesized a premium {t} platform for you. By analyzing your requirements through our neural architecture, I've optimized the visual flow for maximum client engagement. Notice the {self.config['theme']} aesthetic which emphasizes your brand's authority. Your site is fully responsive, SEO-optimized, and ready for immediate deployment. Shall I explain the technical implementation further?"

    def _build_html(self, imgs):
        bg = "bg-black text-white" if self.config['theme'] == 'dark' else "bg-white text-gray-900"
        accent = self.config['accent']
        
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self.config['name']} | Generated by AI Site Architect</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body class="{bg} antialiased">
    <!-- Navbar -->
    <nav class="fixed top-0 w-full z-50 bg-white/10 backdrop-blur-md border-b border-white/10 px-8 py-4 flex justify-between items-center">
        <div class="text-2xl font-black tracking-tighter">AI.<span style="color:{accent}">SYNTH</span></div>
        <div class="space-x-8 text-sm font-bold opacity-70">
            <a href="#home">Home</a>
            <a href="#services">Services</a>
            <a href="#contact">Contact</a>
        </div>
    </nav>

    <!-- Hero -->
    <header id="home" class="min-h-screen flex items-center justify-center relative overflow-hidden px-8">
        <div class="absolute inset-0 z-0">
            <img src="{imgs['hero']}" class="w-full h-full object-cover opacity-30">
            <div class="absolute inset-0 bg-gradient-to-b from-transparent to-black"></div>
        </div>
        <div class="relative z-10 text-center max-w-4xl">
            <span class="px-4 py-1 rounded-full bg-white/10 text-[10px] font-black uppercase tracking-widest mb-6 inline-block">Neural Synthesized UI v2.0</span>
            <h1 class="text-7xl md:text-9xl font-black mb-8 leading-[0.9]">Elevate Your <span style="color:{accent}">{self.config['type']}</span></h1>
            <p class="text-xl opacity-60 mb-10 max-w-2xl mx-auto">Digitally architected for performance. Seamlessly integrated for scale.</p>
            <div class="flex gap-4 justify-center">
                <button class="px-12 py-5 rounded-2xl font-black shadow-2xl transition-all hover:scale-105" style="background-color:{accent}">GET STARTED</button>
            </div>
        </div>
    </header>

    <!-- Featured Images -->
    <section id="services" class="py-32 px-8 grid grid-cols-1 md:grid-cols-3 gap-8 max-w-7xl mx-auto">
        <div class="rounded-[3rem] overflow-hidden group relative h-96">
            <img src="{imgs['feat1']}" class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700">
            <div class="absolute inset-0 bg-black/40 flex items-end p-10">
                <h3 class="text-3xl font-black">Innovation</h3>
            </div>
        </div>
        <div class="rounded-[3rem] overflow-hidden group relative h-96">
            <img src="{imgs['feat2']}" class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700">
            <div class="absolute inset-0 bg-black/40 flex items-end p-10">
                <h3 class="text-3xl font-black">Scalability</h3>
            </div>
        </div>
        <div class="rounded-[3rem] overflow-hidden group relative h-96">
            <img src="{imgs['feat3']}" class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700">
            <div class="absolute inset-0 bg-black/40 flex items-end p-10">
                <h3 class="text-3xl font-black">Performance</h3>
            </div>
        </div>
    </section>

    <footer class="py-20 text-center opacity-30 text-xs uppercase tracking-widest border-t border-white/10">
        &copy; 2026 {self.config['name']} | Synthesized by Admitionwala AI Site Architect
    </footer>

    <script src="assets/js/main.js"></script>
</body>
</html>"""

    def _build_css(self):
        return """
        @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@400;700;900&display=swap');
        body { font-family: 'Outfit', sans-serif; scroll-behavior: smooth; }
        .smooth-shadow { box-shadow: 0 30px 60px -12px rgba(0,0,0,0.25), 0 18px 36px -18px rgba(0,0,0,0.3); }
        """

    def _build_js(self):
        return """
        console.log('AI Synthesized JS: Success');
        document.addEventListener('DOMContentLoaded', () => {
            // Neural scroll mapping
            window.addEventListener('scroll', () => {
                const nav = document.querySelector('nav');
                if(window.scrollY > 50) nav.classList.add('bg-black/80');
                else nav.classList.remove('bg-black/80');
            });
        });
        """

    def _build_readme(self):
        return f"""# Generated Project: {self.config['name']}
Created by: Admitionwala AI Site Architect v2.0

## Synthesis Parameters
- **Industry:** {self.config['type']}
- **Theme:** {self.config['theme']}
- **Accent:** {self.config['accent']}

## Next Steps
1. Unzip the package.
2. Open `index.html` in any browser.
3. Integrate your specific brand assets into the `assets/` directory.

---
*Optimized for professional deployment.*
"""
